/* Pedido de Atendimento Interfilial
   Firebird 2.5+.
   Executar antes de disponibilizar a nova entrada de pedido aos usuarios.
*/

CREATE TABLE PEDATENDIMENTO (
    ID_PEDATENDIMENTO INTEGER NOT NULL,
    ID_PEDVENDA INTEGER NOT NULL,
    ID_PESSOA_EMP_VENDA INTEGER NOT NULL,
    ID_PESSOA_EMP_ATEND INTEGER NOT NULL,
    ID_PESSOA_CLI INTEGER NOT NULL,
    ID_USUARIO_WEB INTEGER NOT NULL,
    FORMA_ATENDIMENTO CHAR(1) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    DATA_ACORDADA DATE NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    OBSERVACAO VARCHAR(500),
    CONSTRAINT PK_PEDATENDIMENTO PRIMARY KEY (ID_PEDATENDIMENTO),
    CONSTRAINT CK_PEDATEND_FORMA CHECK (
        FORMA_ATENDIMENTO IN ('E', 'R', 'T')
    )
);

CREATE TABLE PEDATENDITEM (
    ID_PEDATENDITEM INTEGER NOT NULL,
    ID_PEDATENDIMENTO INTEGER NOT NULL,
    ID_PEDVENDAITEM INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    ID_LOCALIDADE INTEGER NOT NULL,
    ID_PRODUTOLOTE INTEGER,
    QUANTIDADE DECIMAL(18,3) NOT NULL,
    OBSERVACAO VARCHAR(500),
    CONSTRAINT PK_PEDATENDITEM PRIMARY KEY (ID_PEDATENDITEM),
    CONSTRAINT FK_PEDATENDITEM_ATEND FOREIGN KEY (ID_PEDATENDIMENTO)
        REFERENCES PEDATENDIMENTO (ID_PEDATENDIMENTO)
);

CREATE GENERATOR GEN_PEDATENDIMENTO_ID;
CREATE GENERATOR GEN_PEDATENDITEM_ID;

SET GENERATOR GEN_PEDATENDIMENTO_ID TO 0;
SET GENERATOR GEN_PEDATENDITEM_ID TO 0;

CREATE UNIQUE INDEX UNQ_PEDATEND_CHAVE
    ON PEDATENDIMENTO (
        ID_PEDVENDA,
        ID_PESSOA_EMP_ATEND,
        FORMA_ATENDIMENTO,
        DATA_ACORDADA
    );

CREATE INDEX IDX_PEDATEND_PEDVENDA
    ON PEDATENDIMENTO (ID_PEDVENDA);

CREATE INDEX IDX_PEDATEND_EMP_STATUS
    ON PEDATENDIMENTO (ID_PESSOA_EMP_ATEND, STATUS, DATA_ACORDADA);

CREATE INDEX IDX_PEDATENDITEM_PEDITEM
    ON PEDATENDITEM (ID_PEDVENDAITEM);

CREATE INDEX IDX_PEDATENDITEM_ATEND
    ON PEDATENDITEM (ID_PEDATENDIMENTO);
